resources:
- repo: self
trigger:
- master
queue:
  name: Hosted Ubuntu 1604
steps:
- task: PythonScript@0
  displayName: Create input parameters
  inputs:
    scriptSource:  filePath
    scriptPath:  create-input-parameters.py
    arguments:  'deploy.parameters.json projects.json'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/content'
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)/content'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: content'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/content'
    ArtifactName: content